### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by magnusvk** [spree/spree_auth_devise#146]
When I try running the tests on master, I get a bunch of failures. I don't have the time to dive in and fix them right now, but we should work towards making these pass again.

```
Failures:

  1) Spree::CheckoutController#edit when registration step enabled when authenticated as registered user should proceed to the first checkout step
     Failure/Error: spree_get :edit, { :state => 'address' }
       Double "Spree::User_1007" received unexpected message :ship_address with (no args)
     # ./spec/controllers/spree/checkout_controller_spec.rb:24:in `block (5 levels) in <top (required)>'

  2) Spree::CheckoutController#edit when registration step disabled when authenticated as registered should proceed to the first checkout step
     Failure/Error: spree_get :edit, { :state => 'address' }
       Double "Spree::User_1008" received unexpected message :ship_address with (no args)
     # ./spec/controllers/spree/checkout_controller_spec.rb:47:in `block (5 levels) in <top (required)>'

  3) Spree::CheckoutController#update_registration should render the registration view if unable to save
     Failure/Error: flash[:registration_error].should == I18n.t(:email_is_invalid, :scope => [:errors, :messages])
       expected: "Email address cannot be blank"
            got: nil (using ==)
     # ./spec/controllers/spree/checkout_controller_spec.rb:126:in `block (3 levels) in <top (required)>'

  4) Accounts editing should be able to edit a new user
     Failure/Error: click_link "My Account"
     Capybara::ElementNotFound:
       Unable to find link "My Account"
     # ./spec/features/account_spec.rb:24:in `block (3 levels) in <top (required)>'

  5) Accounts editing should be able to edit an existing user account
     Failure/Error: user = create(:user, :email => "email@person.com", :password => "secret", :password_confirmation => "secret")
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
     # ./spec/features/account_spec.rb:36:in `block (3 levels) in <top (required)>'

  6) Checkout without payment being required should allow a visitor to checkout as guest, without registration
     Failure/Error: select "#{address.state.name}", :from => "order_#{str_addr}_attributes_state_id"
     Capybara::ElementNotFound:
       Unable to find select box "order_bill_address_attributes_state_id"
     # ./spec/features/checkout_spec.rb:52:in `block (3 levels) in <top (required)>'

  7) Checkout without payment being required should associate an uncompleted guest order with user after logging in
     Failure/Error: select "#{address.state.name}", :from => "order_#{str_addr}_attributes_state_id"
     Capybara::ElementNotFound:
       Unable to find select box "order_bill_address_attributes_state_id"
     # ./spec/features/checkout_spec.rb:80:in `block (3 levels) in <top (required)>'

  8) Checkout without payment being required should associate an incomplete guest order with user after successful password reset
     Failure/Error: select "#{address.state.name}", :from => "order_#{str_addr}_attributes_state_id"
     Capybara::ElementNotFound:
       Unable to find select box "order_bill_address_attributes_state_id"
     # ./spec/features/checkout_spec.rb:114:in `block (3 levels) in <top (required)>'

  9) Checkout without payment being required should allow a user to register during checkout
     Failure/Error: select "#{address.state.name}", :from => "order_#{str_addr}_attributes_state_id"
     Capybara::ElementNotFound:
       Unable to find select box "order_bill_address_attributes_state_id"
     # ./spec/features/checkout_spec.rb:138:in `block (3 levels) in <top (required)>'

  10) Orders should allow a user to view their cart at any time
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/stylesheets/spree/frontend/all.css"
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/server.rb:19:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

  11) Orders should merge incomplete orders from different sessions
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/stylesheets/spree/frontend/all.css"
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/server.rb:19:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

  12) Reset Password should allow a user to supply an email for the password reset
     Failure/Error: page.should have_content("You will receive an email with instructions")
       expected to find text "You will receive an email with instructions" in "Login All departments Home Cart: (Empty) 1 error prohibited this record from being saved: There were problems with the following fields: Email not found Forgot Password? Please enter your email on the form below Email Powered by Spree"
     # ./spec/features/password_reset_spec.rb:14:in `block (2 levels) in <top (required)>'

  13) Reset Password shows errors if no email is supplied
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/stylesheets/spree/frontend/all.css"
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/server.rb:19:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

  14) promotion adjustments provides a promotion for the first order for a new user doesn't blow up the signup page
     Failure/Error: select2 "User signup", :from => "Event"
     RuntimeError:
       Could not find label by text Event
     # ./spec/features/promotion_adjustment_spec.rb:40:in `block (3 levels) in <top (required)>'

  15) promotion adjustments provides a promotion for the first order for a new user with an order correctly applies the adjustment if a user signs up as a real user
     Failure/Error: select2 "User signup", :from => "Event"
     RuntimeError:
       Could not find label by text Event
     # ./spec/features/promotion_adjustment_spec.rb:40:in `block (3 levels) in <top (required)>'

  16) promotion adjustments provides a promotion for the first order for a new user without an order signing up, then placing an order
     Failure/Error: select2 "User signup", :from => "Event"
     RuntimeError:
       Could not find label by text Event
     # ./spec/features/promotion_adjustment_spec.rb:40:in `block (3 levels) in <top (required)>'

  17) Sign In should ask use to sign in
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/stylesheets/spree/frontend/all.css"
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/server.rb:19:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

  18) Sign In should let a user sign in successfully
     Failure/Error: page.should have_content("Logged in successfully")
       expected to find text "Logged in successfully" in "Login All departments Home Cart: (Empty) Invalid email or password. Login as Existing Customer Email Password Remember me or Create a new account | Forgot Password? Powered by Spree"
     # ./spec/features/sign_in_spec.rb:18:in `block (2 levels) in <top (required)>'

  19) Sign In should show validation erros
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/stylesheets/spree/frontend/all.css"
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/server.rb:19:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

  20) Sign In should allow a user to access a restricted page after logging in
     Failure/Error: page.should have_content("Logged in as: admin@person.com")
       expected to find text "Logged in as: admin@person.com" in "Login All departments Home Cart: (Empty) Invalid email or password. Login as Existing Customer Email Password Remember me or Create a new account | Forgot Password? Powered by Spree"
     # ./spec/features/sign_in_spec.rb:38:in `block (2 levels) in <top (required)>'

  21) Sign Out should allow a signed in user to logout
     Failure/Error: click_link "Logout"
     Capybara::ElementNotFound:
       Unable to find link "Logout"
     # ./spec/features/sign_out_spec.rb:21:in `block (2 levels) in <top (required)>'

  22) Sign Up with valid data should create a new user
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/stylesheets/spree/frontend/all.css"
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/server.rb:19:in `call'
     # /Users/magnusvk/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
     # /Users/magnusvk/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

  23) Sign Up with invalid data should not create a new user
     Failure/Error: Spree::User.count.should == 0
       expected: 0
            got: 1 (using ==)
     # ./spec/features/sign_up_spec.rb:24:in `block (3 levels) in <top (required)>'

  24) Users admin editing email with validation error
     Failure/Error: click_link "Users"
     Capybara::ElementNotFound:
       Unable to find link "Users"
     # ./spec/features/user_spec.rb:11:in `block (2 levels) in <top (required)>'

  25) Users admin editing roles
     Failure/Error: click_link "Users"
     Capybara::ElementNotFound:
       Unable to find link "Users"
     # ./spec/features/user_spec.rb:11:in `block (2 levels) in <top (required)>'

  26) Spree::Order with bogus email should not be valid
     Failure/Error: order.should_not be_valid
       expected #<Spree::Order id: nil, number: nil, item_total: #<BigDecimal:7fed729b3bf8,'0.0',9(18)>, total: #<BigDecimal:7fed729b3a90,'0.0',9(18)>, state: "address", adjustment_total: #<BigDecimal:7fed729b3450,'0.0',9(18)>, user_id: nil, completed_at: nil, bill_address_id: nil, ship_address_id: nil, payment_total: #<BigDecimal:7fed729b2848,'0.0',9(18)>, shipping_method_id: nil, shipment_state: nil, payment_state: nil, email: "foo", special_instructions: nil, created_at: nil, updated_at: nil, currency: "USD", last_ip_address: nil, created_by_id: nil, shipment_total: #<BigDecimal:7fed729b10b0,'0.0',9(18)>, additional_tax_total: #<BigDecimal:7fed729b0b38,'0.0',9(18)>, promo_total: #<BigDecimal:7fed729bb510,'0.0',9(18)>, channel: "spree", included_tax_total: #<BigDecimal:7fed729b9530,'0.0',9(18)>> not to be valid
     # ./spec/models/order_spec.rb:33:in `block (3 levels) in <top (required)>'

Finished in 1 minute 27.21 seconds
75 examples, 26 failures, 1 pending
```
